name: NPM Test
on:
  push:
    branches:
    - master
    pull_request:
    - master
jobs:
  npm-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - run: npx standard
  # npm-pack:
  #   runs-on: ubuntu-latest
  #   needs: npm-lint
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: latest
  #   - run: npm version
  #   - run: npm pack
  #   - run: ls *.tgz
  #   - run: git status
  npm-test:
    needs: npm-lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [latest]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  npm-publish:
    runs-on: ubuntu-latest
    needs: npm-test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - run: npm ci
    - run: npm run build --if-present
    - run: npm publish
      if: startsWith(github.ref, 'refs/heads/master')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.node_auth_token }}

# # name: Release NPM package
# # on:
# #   workflow_dispatch:
# #     inputs:
# #       npm-version-new:
# #         required: true
# #         type: choice
# #         description: NPM New Version Type
# #         options:
# #         - major
# #         - minor
# #         - patch
# #         - premajor
# #         - preminor
# #         - prepatch
# #         - prerelease
# #         - from-git
# # jobs:
# #   npm-lint:
# #   npm-test:
# #   # does the build and runs the test
# #   npm-build:
# #   # basically does the `npm install` and the npm pack

# #   release:
# #     runs-on: ubuntu-latest
# #     steps:
# #     - uses: actions/checkout@v2.3.4
# #     - uses: actions/setup-node@v2
# #       with:
# #         node-version: 19
# #         registry-url: https://registry.npmjs.org/
# # #     - run: |
# # #         # git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
# # #         # git config --global user.name "GitHub Actions"

